### ISSUE TITLE
sp_IndexCleanup

### ISSUE THREAD

**Issue by leonardolombardo** [erikdarlingdata/DarlingData#476] opened 2024-10-09 15:18 UTC
**Version of the script**
        @version = '-2147483648',
        @version_date = '17530101';

**What is the current behavior?**
Executed with default parameters it completes but with the following error:

Error occurred: Cannot insert the value NULL into column 'database_id', table 'tempdb.dbo.#index_analysis_____________________________________________________________________________________________________000000A80594'; column does not allow nulls. INSERT fails.

**If the current behavior is a bug, please provide the steps to reproduce.**
EXEC sp_IndexCleanup

**What is the expected behavior?**
I don't know, it's the first run.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64) 
	Sep 24 2019 13:48:23 
	Copyright (C) 2019 Microsoft Corporation
	Developer Edition (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervisor)

**Comment by erikdarlingdata** [comment] 2024-10-09 15:35
HAHAHA, that doesn't happen for me locally, but I can totally see why that would happen somewhere else. This should be fixed now.

**Closed by erikdarlingdata** 2024-10-09 15:35 UTC
Labels: bug, sp_IndexCleanup

**Comment by leonardolombardo** [comment] 2024-10-09 15:55
With this version

        @version = '-2147483648',
        @version_date = '17530101';

 I get a different error:

Warning: The join order has been enforced because a local join hint is used.
Error occurred: Violation of PRIMARY KEY constraint 'PK__#index_a__0E32247C47215F50'. Cannot insert duplicate key in object 'dbo.#index_analysis'. The duplicate key value is (Allergen, IX_Allergen_1).

**Comment by erikdarlingdata** [comment] 2024-10-09 16:00
That’s a real interesting one. I’ve changed the index to be non-unique.

From: Leonardo Lombardo ***@***.***>
Date: Wednesday, October 9, 2024 at 11:55 AM
To: erikdarlingdata/DarlingData ***@***.***>
Cc: Erik Darling ***@***.***>, State change ***@***.***>
Subject: Re: [erikdarlingdata/DarlingData] sp_IndexCleanup (Issue #476)

With this version

    @version = '-2147483648',

    @version_date = '17530101';

I get a different error:

Warning: The join order has been enforced because a local join hint is used.
Error occurred: Violation of PRIMARY KEY constraint 'PK__#index_a__0E32247C47215F50'. Cannot insert duplicate key in object 'dbo.#index_analysis'. The duplicate key value is (Allergen, IX_Allergen_1).

**Comment by erikdarlingdata** [comment] 2024-10-10 11:26
@leonardolombardo okay, great, this is where open source fun kicks in: I don't have access to your server, so I can't troubleshoot this part for you. 

What I can tell you is that there are no LEFT or SUBSTRING functions in the query you posted up there, so this isn't where the error happened.

If you want to do the work to figure the error out, cool. You can either submit a pull request or tell me which query the problem is in. Just open a new issue for that and provide as much detail as possible.

Thanks!
