### ISSUE TITLE
Stored procedure creation script does not complete on SQL Server 2017 Web Edition

### ISSUE THREAD

**Issue by william001** [erikdarlingdata/DarlingData#79] opened 2021-02-18 18:18 UTC
**Version of the script**
@version = '1.5', @version_date = '20200501'

**What is the current behavior?**
When attempting to run the install script on SQL Server 2017 Web Edition (14.0.3370.1), the initial, almost empty stored procedure is created. However, the rest of the script throws the errors below:
```
Msg 156, Level 15, State 1, Line 16
Incorrect syntax near the keyword 'PROCEDURE'.
Msg 156, Level 15, State 1, Line 20
Incorrect syntax near the keyword 'BEGIN'.
Msg 137, Level 15, State 1, Line 23
Must declare the scalar variable "@version".
Msg 137, Level 15, State 2, Line 25
Must declare the scalar variable "@help".
Msg 137, Level 15, State 2, Line 307
Must declare the scalar variable "@keep_alive".
Msg 137, Level 15, State 2, Line 309
Must declare the scalar variable "@event_type".
Msg 137, Level 15, State 2, Line 311
Must declare the scalar variable "@keep_alive".
Msg 137, Level 15, State 2, Line 313
Must declare the scalar variable "@event_type".
Msg 156, Level 15, State 1, Line 315
Incorrect syntax near the keyword 'IF'.
Msg 137, Level 15, State 2, Line 317
Must declare the scalar variable "@max_memory_kb".
Msg 319, Level 15, State 1, Line 318
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
Msg 137, Level 15, State 1, Line 319
Must declare the scalar variable "@max_memory_kb".
Msg 137, Level 15, State 2, Line 326
Must declare the scalar variable "@max_memory_kb".
Msg 137, Level 15, State 2, Line 384
Must declare the scalar variable "@event_type".
Msg 137, Level 15, State 2, Line 385
Must declare the scalar variable "@client_app_name".
Msg 137, Level 15, State 2, Line 386
Must declare the scalar variable "@client_hostname".
Msg 137, Level 15, State 2, Line 387
Must declare the scalar variable "@database_name".
Msg 137, Level 15, State 2, Line 388
Must declare the scalar variable "@session_id".
Msg 137, Level 15, State 2, Line 389
Must declare the scalar variable "@username".
Msg 137, Level 15, State 2, Line 390
Must declare the scalar variable "@object_name".
Msg 137, Level 15, State 2, Line 391
Must declare the scalar variable "@object_schema".
Msg 137, Level 15, State 2, Line 392
Must declare the scalar variable "@custom_name".
Msg 137, Level 15, State 2, Line 393
Must declare the scalar variable "@output_database_name".
Msg 137, Level 15, State 2, Line 394
Must declare the scalar variable "@output_schema_name".
Msg 137, Level 15, State 2, Line 395
Must declare the scalar variable "@database_name".
Msg 137, Level 15, State 2, Line 396
Must declare the scalar variable "@database_name".
Msg 137, Level 15, State 2, Line 399
Must declare the scalar variable "@event_type".
Msg 137, Level 15, State 2, Line 403
Must declare the scalar variable "@event_type".
Msg 319, Level 15, State 1, Line 404
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
Msg 137, Level 15, State 2, Line 409
Must declare the scalar variable "@event_type".
Msg 137, Level 15, State 1, Line 421
Must declare the scalar variable "@query_duration_ms".
Msg 137, Level 15, State 2, Line 425
Must declare the scalar variable "@event_type".
Msg 137, Level 15, State 1, Line 436
Must declare the scalar variable "@wait_duration_ms".
Msg 137, Level 15, State 2, Line 440
Must declare the scalar variable "@event_type".
Msg 137, Level 15, State 1, Line 451
Must declare the scalar variable "@blocking_duration_ms".
Msg 137, Level 15, State 2, Line 455
Must declare the scalar variable "@query_sort_order".
Msg 137, Level 15, State 2, Line 457
Must declare the scalar variable "@query_sort_order".
Msg 319, Level 15, State 1, Line 458
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
Msg 137, Level 15, State 1, Line 459
Must declare the scalar variable "@query_sort_order".
Msg 137, Level 15, State 2, Line 463
Must declare the scalar variable "@wait_type".
Msg 137, Level 15, State 2, Line 470
Must declare the scalar variable "@wait_type".
Msg 137, Level 15, State 2, Line 473
Must declare the scalar variable "@wait_type".
Msg 137, Level 15, State 2, Line 477
Must declare the scalar variable "@wait_type".
Msg 137, Level 15, State 2, Line 498
Must declare the scalar variable "@client_app_name".
Msg 137, Level 15, State 2, Line 516
Must declare the scalar variable "@client_app_name".
Msg 137, Level 15, State 2, Line 543
Must declare the scalar variable "@wait_type".
Msg 137, Level 15, State 2, Line 553
Must declare the scalar variable "@event_type".
Msg 137, Level 15, State 2, Line 561
Must declare the scalar variable "@event_type".
Msg 137, Level 15, State 2, Line 565
Must declare the scalar variable "@fully_formed_babby".
Msg 319, Level 15, State 1, Line 566
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
Msg 137, Level 15, State 2, Line 571
Must declare the scalar variable "@event_type".
Msg 137, Level 15, State 2, Line 591
Must declare the scalar variable "@database_name".
Msg 137, Level 15, State 2, Line 593
Must declare the scalar variable "@database_name".
Msg 137, Level 15, State 2, Line 595
Must declare the scalar variable "@database_name".
Msg 319, Level 15, State 1, Line 596
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
Msg 137, Level 15, State 2, Line 602
Must declare the scalar variable "@session_id".
Msg 137, Level 15, State 2, Line 606
Must declare the scalar variable "@session_id".
Msg 319, Level 15, State 1, Line 607
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
Msg 137, Level 15, State 2, Line 612
Must declare the scalar variable "@sample_divisor".
Msg 137, Level 15, State 2, Line 623
Must declare the scalar variable "@seconds_sample".
Msg 137, Level 15, State 2, Line 626
Must declare the scalar variable "@seconds_sample".
Msg 137, Level 15, State 2, Line 628
Must declare the scalar variable "@gimme_danger".
Msg 137, Level 15, State 2, Line 641
Must declare the scalar variable "@seconds_sample".
Msg 137, Level 15, State 2, Line 642
Must declare the scalar variable "@seconds_sample".
Msg 137, Level 15, State 2, Line 648
Must declare the scalar variable "@seconds_sample".
Msg 137, Level 15, State 2, Line 684
Must declare the scalar variable "@output_database_name".
Msg 137, Level 15, State 2, Line 686
Must declare the scalar variable "@output_database_name".
Msg 137, Level 15, State 2, Line 688
Must declare the scalar variable "@output_database_name".
Msg 319, Level 15, State 1, Line 689
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
Msg 137, Level 15, State 2, Line 695
Must declare the scalar variable "@output_schema_name".
Msg 137, Level 15, State 2, Line 699
Must declare the scalar variable "@output_database_name".
Msg 137, Level 15, State 2, Line 702
Must declare the scalar variable "@s_sql".
Msg 137, Level 15, State 2, Line 703
Must declare the scalar variable "@s_out".
Msg 137, Level 15, State 2, Line 705
Must declare the scalar variable "@output_schema_name".
Msg 137, Level 15, State 2, Line 711
Must declare the scalar variable "@output_database_name".
Msg 137, Level 15, State 2, Line 716
Must declare the scalar variable "@output_database_name".
Msg 137, Level 15, State 2, Line 722
Must declare the scalar variable "@output_schema_name".
Msg 137, Level 15, State 2, Line 731
Must declare the scalar variable "@custom_name".
Msg 137, Level 15, State 2, Line 734
Must declare the scalar variable "@custom_name".
Msg 319, Level 15, State 1, Line 735
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
Msg 137, Level 15, State 2, Line 736
Must declare the scalar variable "@custom_name".
Msg 319, Level 15, State 1, Line 737
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
Msg 137, Level 15, State 2, Line 742
Must declare the scalar variable "@delete_retention_days".
Msg 137, Level 15, State 1, Line 744
Must declare the scalar variable "@delete_retention_days".
Msg 137, Level 15, State 2, Line 750
Must declare the scalar variable "@output_database_name".
Msg 137, Level 15, State 2, Line 764
Must declare the scalar variable "@output_database_name".
Msg 137, Level 15, State 2, Line 775
Must declare the scalar variable "@query_duration_ms".
Msg 137, Level 15, State 2, Line 777
Must declare the scalar variable "@event_type".
Msg 137, Level 15, State 2, Line 779
Must declare the scalar variable "@query_duration_ms".
Msg 137, Level 15, State 2, Line 782
Must declare the scalar variable "@blocking_duration_ms".
Msg 137, Level 15, State 2, Line 784
Must declare the scalar variable "@blocking_duration_ms".
Msg 137, Level 15, State 2, Line 786
Must declare the scalar variable "@wait_duration_ms".
Msg 137, Level 15, State 2, Line 788
Must declare the scalar variable "@wait_duration_ms".
Msg 137, Level 15, State 2, Line 790
Must declare the scalar variable "@client_app_name".
Msg 137, Level 15, State 2, Line 792
Must declare the scalar variable "@client_app_name".
Msg 137, Level 15, State 2, Line 794
Must declare the scalar variable "@client_hostname".
Msg 137, Level 15, State 2, Line 796
Must declare the scalar variable "@client_hostname".
Msg 137, Level 15, State 2, Line 798
Must declare the scalar variable "@database_name".
Msg 137, Level 15, State 2, Line 800
Must declare the scalar variable "@event_type".
Msg 137, Level 15, State 2, Line 802
Must declare the scalar variable "@database_name".
Msg 137, Level 15, State 2, Line 804
Must declare the scalar variable "@event_type".
Msg 137, Level 15, State 2, Line 806
Must declare the scalar variable "@database_name".
Msg 137, Level 15, State 2, Line 809
Must declare the scalar variable "@session_id".
Msg 137, Level 15, State 2, Line 811
Must declare the scalar variable "@session_id".
Msg 137, Level 15, State 2, Line 813
Must declare the scalar variable "@session_id".
Msg 137, Level 15, State 2, Line 815
Must declare the scalar variable "@session_id".
Msg 137, Level 15, State 2, Line 817
Must declare the scalar variable "@sample_divisor".
Msg 137, Level 15, State 2, Line 820
Must declare the scalar variable "@username".
Msg 137, Level 15, State 2, Line 822
Must declare the scalar variable "@username".
Msg 137, Level 15, State 2, Line 824
Must declare the scalar variable "@object_name".
Msg 137, Level 15, State 2, Line 826
Must declare the scalar variable "@event_type".
Msg 137, Level 15, State 2, Line 829
Must declare the scalar variable "@fully_formed_babby".
Msg 137, Level 15, State 2, Line 832
Must declare the scalar variable "@event_type".
Msg 137, Level 15, State 2, Line 834
Must declare the scalar variable "@object_name".
Msg 137, Level 15, State 2, Line 837
Must declare the scalar variable "@requested_memory_mb".
Msg 137, Level 15, State 2, Line 839
Must declare the scalar variable "@requested_memory_mb".
Msg 137, Level 15, State 2, Line 840
Must declare the scalar variable "@requested_memory_kb".
Msg 137, Level 15, State 2, Line 842
Must declare the scalar variable "@event_type".
Msg 137, Level 15, State 2, Line 850
Must declare the scalar variable "@wait_type".
Msg 137, Level 15, State 2, Line 854
Must declare the scalar variable "@wait_type".
Msg 137, Level 15, State 2, Line 885
Must declare the scalar variable "@event_type".
Msg 137, Level 15, State 2, Line 943
Must declare the scalar variable "@session_with".
Msg 137, Level 15, State 2, Line 944
Must declare the scalar variable "@debug".
Msg 137, Level 15, State 2, Line 950
Must declare the scalar variable "@debug".
Msg 137, Level 15, State 2, Line 956
Must declare the scalar variable "@keep_alive".
Msg 137, Level 15, State 2, Line 995
Must declare the scalar variable "@debug".
Msg 137, Level 15, State 2, Line 1001
Must declare the scalar variable "@event_type".
Msg 137, Level 15, State 2, Line 1034
Must declare the scalar variable "@debug".
Msg 319, Level 15, State 1, Line 1041
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
Msg 137, Level 15, State 2, Line 1140
Must declare the scalar variable "@debug".
Msg 319, Level 15, State 1, Line 1147
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
Msg 137, Level 15, State 2, Line 1229
Must declare the scalar variable "@query_sort_order".
Msg 137, Level 15, State 2, Line 1232
Must declare the scalar variable "@event_type".
Msg 137, Level 15, State 2, Line 1252
Must declare the scalar variable "@debug".
Msg 319, Level 15, State 1, Line 1259
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
Msg 137, Level 15, State 2, Line 1298
Must declare the scalar variable "@debug".
Msg 137, Level 15, State 2, Line 1339
Must declare the scalar variable "@debug".
Msg 319, Level 15, State 1, Line 1346
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
Msg 137, Level 15, State 2, Line 1385
Must declare the scalar variable "@event_type".
Msg 137, Level 15, State 2, Line 1404
Must declare the scalar variable "@debug".
Msg 319, Level 15, State 1, Line 1411
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
Msg 137, Level 15, State 2, Line 1452
Must declare the scalar variable "@debug".
Msg 137, Level 15, State 2, Line 1469
Must declare the scalar variable "@event_type".
Msg 137, Level 15, State 2, Line 1485
Must declare the scalar variable "@gimme_danger".
Msg 137, Level 15, State 2, Line 1490
Must declare the scalar variable "@debug".
Msg 137, Level 15, State 2, Line 1550
Must declare the scalar variable "@event_type".
Msg 137, Level 15, State 2, Line 1579
Must declare the scalar variable "@debug".
Msg 137, Level 15, State 2, Line 1613
Must declare the scalar variable "@debug".
Msg 137, Level 15, State 2, Line 1648
Must declare the scalar variable "@keep_alive".
Msg 137, Level 15, State 2, Line 1650
Must declare the scalar variable "@debug".
Msg 137, Level 15, State 2, Line 1658
Must declare the scalar variable "@debug".
Msg 137, Level 15, State 2, Line 1701
Must declare the scalar variable "@debug".
Msg 137, Level 15, State 2, Line 1731
Must declare the scalar variable "@output_database_name".
Msg 137, Level 15, State 2, Line 1766
Must declare the scalar variable "@debug".
Msg 137, Level 15, State 2, Line 1803
Must declare the scalar variable "@debug".
Msg 137, Level 15, State 2, Line 1816
Must declare the scalar variable "@debug".
Msg 137, Level 15, State 2, Line 1828
Must declare the scalar variable "@debug".
Msg 137, Level 15, State 2, Line 1913
Must declare the scalar variable "@output_database_name".
Msg 319, Level 15, State 1, Line 1914
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
Msg 137, Level 15, State 2, Line 1916
Must declare the scalar variable "@output_database_name".
Msg 137, Level 15, State 2, Line 1940
Must declare the scalar variable "@debug".
Msg 137, Level 15, State 2, Line 1982
Must declare the scalar variable "@debug".
Msg 137, Level 15, State 2, Line 1987
Must declare the scalar variable "@debug".
Msg 137, Level 15, State 2, Line 2003
Must declare the scalar variable "@debug".
Msg 137, Level 15, State 2, Line 2014
Must declare the scalar variable "@debug".
Msg 137, Level 15, State 2, Line 2284
Must declare the scalar variable "@debug".
Msg 137, Level 15, State 2, Line 2304
Must declare the scalar variable "@debug".
Msg 137, Level 15, State 2, Line 2311
Must declare the scalar variable "@debug".
Msg 137, Level 15, State 2, Line 2319
Must declare the scalar variable "@debug".
Msg 137, Level 15, State 2, Line 2331
Must declare the scalar variable "@debug".
Msg 137, Level 15, State 2, Line 2353
Must declare the scalar variable "@debug".
Msg 137, Level 15, State 2, Line 2358
Must declare the scalar variable "@delete_retention_days".
Msg 137, Level 15, State 2, Line 2368
Must declare the scalar variable "@output_database_name".
Msg 137, Level 15, State 2, Line 2377
Must declare the scalar variable "@debug".
Msg 137, Level 15, State 2, Line 2393
Must declare the scalar variable "@output_database_name".
Msg 137, Level 15, State 2, Line 2396
Must declare the scalar variable "@debug".
Msg 137, Level 15, State 2, Line 2398
Must declare the scalar variable "@executer".
Msg 319, Level 15, State 1, Line 2399
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
Msg 137, Level 15, State 2, Line 2403
Must declare the scalar variable "@executer".
Msg 137, Level 15, State 2, Line 2415
Must declare the scalar variable "@output_database_name".
Msg 137, Level 15, State 2, Line 2418
Must declare the scalar variable "@debug".
Msg 137, Level 15, State 2, Line 2420
Must declare the scalar variable "@executer".
Msg 319, Level 15, State 1, Line 2421
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
Msg 137, Level 15, State 2, Line 2425
Must declare the scalar variable "@executer".
Msg 137, Level 15, State 2, Line 2435
Must declare the scalar variable "@output_database_name".
Msg 137, Level 15, State 2, Line 2438
Must declare the scalar variable "@debug".
Msg 137, Level 15, State 2, Line 2446
Must declare the scalar variable "@debug".
Msg 178, Level 15, State 1, Line 2458
A RETURN statement with a return value cannot be used in this context.
Msg 8180, Level 16, State 1, Procedure sp_describe_parameter_encryption, Line 1 [Batch Start Line 15]
Statement(s) could not be prepared.
An error occurred while executing batch. Error message is: Internal error. Metadata for parameter '@pfb85fa3a74bc497b9a6efd2420ed5861' in statement or procedure 'ALTER PROCEDURE dbo.sp_HumanEvents
@event_type sysname=N'query', @query_duration_ms INT=500, @query_sort_order NVARCHAR (10)=N'cpu', @blocking_duration_ms INT=500, @wait_type NVARCHAR (4000)=N'ALL', @wait_duration_ms INT=10, @client_app_name sysname=N'', @client_hostname sysname=N'', @database_name sysname=N'', @session_id NVARCHAR (7)=N'', @sample_divisor INT=5, @username sysname=N'', @object_name sysname=N'', @object_schema sysname=N'dbo', @requested_memory_mb INT=0, @seconds_sample INT=10, @gimme_danger BIT=0, @keep_alive BIT=0, @custom_name NVARCHAR (256)=N'', @output_database_name sysname=N'', @output_schema_name sysname=N'dbo', @delete_retention_days INT=3, @cleanup BIT=0, @max_memory_kb BIGINT=102400, @version VARCHAR (30)=NULL OUTPUT, @version_date DATETIME=NULL OUTPUT, @debug BIT=0, @help BIT=0
WITH RECOMPILE
AS
BEGIN
    SET NOCOUNT, XACT_ABORT ON;
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
    SELECT @version = '1.5',
           @version_date = '20200501';
    IF @help = 1
 ...' is missing in resultset returned by sp_describe_parameter_encryption.

Completion time: 2021-02-18T20:09:06.6604991+02:00
```

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Copy the raw script for sp_HumanEvents.sql from Github 
2. Paste it into SSMS and select the master database from the dropdown. Ensure the database server is running SQL 2017 Web edition. 
3. Run the script. Observe the errors in the messages window.

**What is the expected behavior?**
The stored procedure should be installed in the master database with no errors. The script runs perfectly in SQL Server 2017 development edition.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL Server 2017 Web Edition (14.0.3370.1) on Windows 2012R2. This is the first time I am attempting to run this script.

**Comment by erikdarlingdata** [comment] 2021-03-05 21:05
Hi there -- I don't have a copy of Web Edition to test things on. You didn't mention in the issue if you're willing to work on this or not. Please let me know.

Thanks!

**Comment by william001** [comment] 2021-03-09 14:23
I'm happy to help. I have fairly good SQL skills but I haven't worked on a big script like yours.

**Comment by erikdarlingdata** [comment] 2021-03-09 14:54
Great, thanks! Let me know if I can assist.

**Comment by erikdarlingdata** [comment] 2021-04-07 19:17
It's been about a month, so I'm going to close this out for now. I assume it's not high priority for you. If you decide you want to work on it, just leave a comment here and I'll re-open the issue.

**Comment by Virtualhurst** [comment] 2021-04-08 06:40
Fair enough - it isn't my highest priority. I'll see if I can take a crack at it in the next few weeks.

**Comment by Virtualhurst** [comment] 2021-04-10 10:39
I have managed to solve the particular errors I was experiencing and I have created PR #91. 

1. changes were made to improve compatibility with SQL 2017 web edition:
1. The value of a declared variable could not be set inline. This may be due to Always Encrypted in SSMS rather than 2017. The script is updated to set the value after the declaration.
2. An error occurs when an "IF @debug=1" statement occurs just before a WITH statement. I do not have a fix for this as I don't know what the underlying problem is. The problematic statements have been commented out for now. The error was "Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon."
3. The delete_tracker section use the TIME type which causes an error. The fix was to update to a DATETIME type. The error was "Operand type clash: numeric is incompatible with time"

For point 2, I don't know what the underlying cause of the issue is so I don't have a fix in place. Any suggestions on why an IF statement would cause these problems? The main culprit is included in the screenshot below. I tried putting semi colons before the WITH statement but that made no difference. The only thing that seemed to work was commenting it out. 
![image](https://user-images.githubusercontent.com/2412322/114266962-958ec400-99f9-11eb-9df0-d173129ff4af.png)

**Comment by erikdarlingdata** [comment] 2021-04-10 13:03
Hm, not sure on the `IF` part. Does it happen under a simplified repro in web edition? If it's purely a restriction, then you might need to can work here. I can't take the debug thing out, or have it quoted out by default. You may need to maintain a local copy with compatibility changes in place. 

For the `TIME` fix, are you sure the behavior is the same?

Thanks,
Erik

**Comment by erikdarlingdata** [comment] 2021-07-30 20:54
Been a while on this, so I'm gonna close it out.

**Closed by erikdarlingdata** 2021-07-30 20:54 UTC
